# Generated by Django 3.2 on 2021-04-28 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 28, 9, 30, 53, 491603)),
        ),
    ]
