# Generated by Django 3.2 on 2021-05-01 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0002_alter_recipemodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='preparation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
