# Generated by Django 3.2 on 2021-05-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0003_auto_20210501_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientsmodel',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
