# Generated by Django 3.2 on 2021-05-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0004_alter_recipeingredientsmodel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientsmodel',
            name='amount',
            field=models.PositiveIntegerField(default=-1, null=True),
        ),
    ]
