# Generated by Django 3.2 on 2021-05-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0006_alter_recipeingredientsmodel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientsmodel',
            name='amount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
