# Generated by Django 3.2 on 2021-05-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0007_alter_recipeingredientsmodel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='ingredients',
            field=models.ManyToManyField(default='pomidor', through='cooking.RecipeIngredientsModel', to='cooking.IngredientsModel'),
        ),
    ]
