# Generated by Django 3.2 on 2021-05-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0008_alter_recipemodel_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='ingredients',
            field=models.ManyToManyField(through='cooking.RecipeIngredientsModel', to='cooking.IngredientsModel'),
        ),
    ]
