# Generated by Django 3.2 on 2021-05-05 18:43

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0012_recipeingredientsmodel_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientsmodel',
            name='unit',
            field=models.CharField(choices=[('ml', 'ml'), ('l', 'l'), ('g', 'g'), ('dag', 'dag'), ('kg', 'kg'), ('łyżka', 'łyżka'), ('łyżki', 'łyżki'), ('łyżeczka', 'łyżeczka'), ('łyżeczki', 'łyżeczki'), ('szt.', 'szt.')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='mealtype',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Śniadanie'), ('2', 'Drugie śniadanie'), ('3', 'Lunch do pracy'), ('4', 'Obiad'), ('5', 'Kolacja')], max_length=9, null=True),
        ),
    ]
